#ifndef INIT_SCR
#define INIT_SCR

#define WIDTH_FROM_TOP_LEFT_MAIN_MENU 5
#define WIDTH_FROM_TOP_LEFT_PAIR_SPLITTING 17
#define WIDTH_FROM_TOP_LEFT_SOFT_TOTALS 35
#define WIDTH_FROM_TOP_LEFT_HARD_TOTALS 50
#define WIDTH_FROM_TOP_LEFT_SETTINGS 75
#define WIDTH_FROM_TOP_LEFT_EXIT 100

#endif
