#ifndef INIT_SCR
#define INIT_SCR

#define MENU_MARGIN 2

#define WIDTH_FROM_TOP_LEFT_MAIN_MENU 5
#define WIDTH_FROM_TOP_LEFT_PAIR_SPLITTING 17
#define WIDTH_FROM_TOP_LEFT_SOFT_TOTALS 35
#define WIDTH_FROM_TOP_LEFT_HARD_TOTALS 50
#define WIDTH_FROM_TOP_LEFT_SETTINGS 75
#define WIDTH_FROM_TOP_LEFT_EXIT 100

#define SCREEN_LINE_1 3
#define SCREEN_LINE_2 5
#define SCREEN_LINE_3 7
#define SCREEN_LINE_4 9
#define SCREEN_LINE_5 11
#define SCREEN_LINE_6 13
#define SCREEN_LINE_7 15
#define SCREEN_MARGIN 4

#endif
